name: panvimdoc

on:
  push:
    branches: [main]
    paths:
      - README.md
      - docs/*
      - .github/workflows/panvimdoc.yml

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.DOCS_PAT }}
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: "lsp-echohint"
          version: "NVIM v0.10.0"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: generate docs"
          branch: ${{ github.head_ref }}
