name: Check types

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stevearc/nvim-typecheck-action@v2
